name = "SqState"
uuid = "8d120385-201d-43c1-a82b-e15c39505f50"
authors = ["JingYu Ning <foldfelis@gmail.com> and contributors"]
version = "0.1.0"

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Gaston = "4b11ee91-296f-5714-9832-002c20994614"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Pluto = "c3e4b0f8-55cb-11ea-2926-15256bba5781"

[compat]
julia = "1.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
